astra_db:
  collection_name: "ecommercedata"

embedding_model:
  provider: "openai"
  model_name: "text-embedding-3-small"

retriever:
  top_k: 10

llm:
  provider: "openai"
  model_name: "gpt-4o-mini"